### ISSUE TITLE
Please add latest compiled version

### ISSUE THREAD

**Issue by ghost** [BouKiCHi/moondrv#1]
Hi, can you please add the latest compiled version of MDRV.COM and MOON.BIN at Github? The available versions are older from 2015. Thank you!

And where can I download more songs for MoonDriver?

**Comment by BouKiCHi** [comment]
The latest version could be downloaded as a zip, but I've also added it to Release.

**Comment by ghost** [comment]
Thanks, but as far as I can see it's still an older version -> MOONLOADER VER 160305.
I thought there's also a version of 2017.

**Comment by BouKiCHi** [comment]
The loader has a different versioning system than moon.bin.
VER 160305 is latest version.

https://github.com/BouKiCHi/moondrv/blob/master/moon_loader.asm
